language: rust
rust:
  - nightly

os:
  - linux
  - osx

services:
  - postgresql

before_script:
  - psql -c 'create database cedalion;' -U postgres
  - cargo install diesel_cli
  - diesel migration run
